// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdm0p556hoSjFDUUjkYevc7szgAepdNoA',
    appId: '1:418363139905:web:73d92f8ac629d9da4923c0',
    messagingSenderId: '418363139905',
    projectId: 'budgetlens-bbf14',
    authDomain: 'budgetlens-bbf14.firebaseapp.com',
    storageBucket: 'budgetlens-bbf14.firebasestorage.app',
    measurementId: 'G-3LXM4CTCX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_85SQrn0n34nJhlQzH_ezYERzxf7JYc4',
    appId: '1:418363139905:android:571e3f7d069c4c694923c0',
    messagingSenderId: '418363139905',
    projectId: 'budgetlens-bbf14',
    storageBucket: 'budgetlens-bbf14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTXLQ_mQZYo9O9C9Xi0xpzoYra9VvD6Wo',
    appId: '1:418363139905:ios:7578d59cf1f505504923c0',
    messagingSenderId: '418363139905',
    projectId: 'budgetlens-bbf14',
    storageBucket: 'budgetlens-bbf14.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTXLQ_mQZYo9O9C9Xi0xpzoYra9VvD6Wo',
    appId: '1:418363139905:ios:7578d59cf1f505504923c0',
    messagingSenderId: '418363139905',
    projectId: 'budgetlens-bbf14',
    storageBucket: 'budgetlens-bbf14.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdm0p556hoSjFDUUjkYevc7szgAepdNoA',
    appId: '1:418363139905:web:00bba3460fd120974923c0',
    messagingSenderId: '418363139905',
    projectId: 'budgetlens-bbf14',
    authDomain: 'budgetlens-bbf14.firebaseapp.com',
    storageBucket: 'budgetlens-bbf14.firebasestorage.app',
    measurementId: 'G-RMVN32BNC2',
  );
}
